# Generated by Django 3.0.2 on 2020-04-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
