# Generated by Django 3.0.2 on 2020-04-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(choices=[('Tulip', 'Tulip'), ('Daffodil', 'Daffodil'), ('Poppy', 'Poppy'), ('Sunflower', 'Sunflower'), ('Bluebell', 'Bluebell'), ('Rose', 'Rose'), ('Snowdrop', 'Snowdrop'), ('Cherryblossom', 'Cherry blossom'), ('Orchid', 'Orchid'), ('Iris', 'Iris'), ('Peony', 'Peony'), ('Chrysanthemum', 'Chrysanthemum'), ('Geranium', 'Geranium'), ('Lily', 'Lily'), ('Lotus', 'Lotus'), ('Waterlily', 'Water lily'), ('Dandelion', 'Dandelion'), ('Hyacinth', 'Hyacinth'), ('Daisy', 'Daisy'), ('Crocus', 'Crocus')], default='None', max_length=13),
        ),
    ]
