# Generated by Django 3.0.2 on 2020-04-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0004_auto_20200417_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Picture_model',
        ),
    ]
