# Generated by Django 3.0.2 on 2020-04-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_auto_20200418_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture_model',
            options={'verbose_name_plural': 'Picture_model'},
        ),
    ]
